cfg_loading = cfg_loading or {}
cfg_loading["1"]={content = "等待时间可以抬头活动活动脖子噢！",}
cfg_loading["2"]={content = "在设置界面可以调节音量大小",}
cfg_loading["3"]={content = "点击玩家角色可以打开战术指令界面，多跟队友交流沟通",}
cfg_loading["4"]={content = "后手行动一方可以获得一个减少伤害的Buff",}
cfg_loading["5"]={content = "己方的蜂窝颜色是黄色的，敌方的蜂窝颜色是红色的",}
cfg_loading["6"]={content = "注意敌方身上的状态，有时无需浪费一次输出他也会死的",}
cfg_loading["7"]={content = "王师傅燃烧瓶产生的火在伤害的同时还会造成些许推力",}
cfg_loading["8"]={content = "女王在场！注意绕行！进入到恐惧领地的小朋友会受到伤害噢",}
cfg_loading["9"]={content = "要时刻注意己方或敌方拍拍身上的战意层数",}
cfg_loading["10"]={content = "烬君被攻击时有几率触发替身术，可以完全闪避一次伤害！",}
cfg_loading["11"]={content = "小小坚硬的外壳可以减少自己受到的伤害",}
cfg_loading["12"]={content = "攻击结束后不要和队友腻在一起啦！",}
cfg_loading["13"]={content = "王师傅死亡时会自爆，造成范围伤害和推力",}
cfg_loading["14"]={content = "肥猫每攻击三次就会触发一次被动效果，可以给队友大幅增加攻击力",}
cfg_loading["15"]={content = "打到护盾上的伤害不会触发反弹或吸血，包括陈可爱的被动效果",}
cfg_loading["16"]={content = "小小的滚石有非常强力的推人效果",}
cfg_loading["17"]={content = "悟空要相信自己总会暴击的",}
cfg_loading["18"]={content = "悟空的救命毫毛可以解除状态，并且会在下一回合为自己增加攻击",}
cfg_loading["19"]={content = "冰女，悟空和赛特的大招会从天而降，释放时一定要看头上有没有障碍物噢",}
cfg_loading["20"]={content = "冰女的冰封和减速对拍拍这样的近战非常有效",}
cfg_loading["21"]={content = "小秋的“爱的牺牲”是很好的技能",}
cfg_loading["22"]={content = "叶子的穿云箭距离越远，伤害越高",}
cfg_loading["23"]={content = "各种卡牌都是很有用的，选一种自己喜欢的搭配吧",}
cfg_loading["24"]={content = "每4个小时都可以开一个免费宝箱",}
cfg_loading["25"]={content = "要尽量远离地图边缘，以防被打下河",}
cfg_loading["26"]={content = "酋长生命值越低，输出越高，所以如果打不死酋长，尽量不要打他",}
cfg_loading["27"]={content = "酋长的大招可以连续撞飞敌人",}
cfg_loading["28"]={content = "被王师傅安装了定时炸弹的玩家不要站在队友身边！",}
cfg_loading["29"]={content = "怦怦英雄不仅是我们的游戏名称",}
cfg_loading["30"]={content = "你想成为怦怦英雄么？",}
cfg_loading["31"]={content = "肥喵可以和敌方玩家交换血量，所以要有策略的集火肥喵",}
cfg_loading["32"]={content = "分享游戏有奖励！",}
cfg_loading["33"]={content = "朋友之间可以扫二维码互加好友",}
cfg_loading["34"]={content = "英雄详情界面的左下角有试玩功能",}
cfg_loading["35"]={content = "助攻也会获得一定数量的赏金",}
cfg_loading["36"]={content = "卡牌方案的名称可以自己修改",}
cfg_loading["37"]={content = "匹配界面点击右侧的最近页签可以查找刚才的队友或对手",}
cfg_loading["38"]={content = "互相关注的玩家就是好友了",}
cfg_loading["39"]={content = "好友之间可以1v1切磋",}
cfg_loading["40"]={content = "关注之后就可以观战他的战斗画面了",}
cfg_loading["41"]={content = "小地图是可以拖动的",}
cfg_loading["42"]={content = "升级以后记得领取升级奖励",}
cfg_loading["43"]={content = "大招充能是多方面的，击杀、助攻、伤害、治疗都可以充能大招",}
cfg_loading["44"]={content = "限免英雄可以多玩一玩，万一很适合你呢！",}
cfg_loading["45"]={content = "大招充能是多方面的，击杀、助攻、伤害、治疗都可以充能大招",}
cfg_loading["46"]={content = "等级越高，引导线越短",}
cfg_loading["47"]={content = "没有最强的英雄，只有最强的玩家",}
cfg_loading["48"]={content = "指令配音真的很好听呢",}
cfg_loading["49"]={content = "引导配音真的很好听呢",}
cfg_loading["50"]={content = "小雷的技能都是在锤子位置释放的，所以要尽量躲开敌方小雷的锤子",}
cfg_loading["51"]={content = "小小石化的时候可以阻挡敌方英雄前进",}
cfg_loading["52"]={content = "烬君是所有英雄中最轻的，所以他跳的比其他英雄高一些",}
cfg_loading["53"]={content = "亦燃的盾牌技能可以阻挡攻击，并且让穿过盾牌的玩家受到灼烧效果",}
cfg_loading["54"]={content = "商店中的卡牌页签中每日都有新卡牌出售，性价比很高的噢",}
cfg_loading["55"]={content = "皮肤碎片可以通过每日胜利宝箱产出，分享和夺宝等获得",}
cfg_loading["56"]={content = "合理安排时间，享受健康生活",}
cfg_loading["57"]={content = "下一局一定会有个好队友的！",}
cfg_loading["58"]={content = "下一局一定会有个好队友的！",}
cfg_loading["59"]={content = "下一局一定会有个好队友的！",}
cfg_loading["60"]={content = "下一局一定会有个好队友的！",}
cfg_loading["61"]={content = "远程攻击的距离越远，伤害越高。要合理控制输出距离",}
cfg_loading["62"]={content = "昊的被动是三段跳，昊是通过商城金币夺宝获得的",}
cfg_loading["63"]={content = "昊不造成推力，但是有很强的穿刺能力",}
cfg_loading["64"]={content = "法师的每个技能都受到被动效果的影响",}
cfg_loading["65"]={content = "法师的雷系大招不受风力影响，火系和冰系受风力影响",}
cfg_loading["66"]={content = "骨龙火山地图最右侧的高坡是可以爬上去的",}
cfg_loading["67"]={content = "卡牌最高等级为30级",}
cfg_loading["68"]={content = "卡牌数量不足时，可以使用卡牌碎片升级对应卡牌。平时要努力获得卡牌碎片！",}
cfg_loading["69"]={content = "最好为不同类型的英雄搭配不同效果的卡牌。",}
cfg_loading["70"]={content = "卡牌右侧有筛选功能，可以为你快速列举出你想要类型的卡牌",}
cfg_loading["71"]={content = "排位赛每日9点到24点开放。娱乐模式每日18点-20点开放",}
cfg_loading["72"]={content = "每天18点-21点登陆游戏并且对战一局，可以获得每日福利宝箱，最高开出666钻石",}
cfg_loading["73"]={content = "每天21点登陆可获得深夜令牌，可兑换奖励",}
cfg_loading["74"]={content = "进阶技巧：小秋的吸力可以让卡在墙角的敌人无处可逃，对准头部吸力效果会更好",}
cfg_loading["75"]={content = "进阶技巧：滚石保持和地形平行的方向扔出会飞的较快",}
cfg_loading["76"]={content = "进阶技巧：烬君可以在释放大招之前隐身，使得大招带有暴击效果",}
cfg_loading["77"]={content = "进阶技巧：悟空可以在释放大招之前分身，增加大招攻击力",}
cfg_loading["78"]={content = "进阶技巧：多数技能使用之后还是可以移动的，尽量抓紧和队友分开",}
cfg_loading["79"]={content = "进阶技巧：肥喵的变形术可以破除烬君的替身、石头人的石化等",}
cfg_loading["80"]={content = "进阶技巧：干脆的大招如果想打一个人，那最好不要用最大力度",}
cfg_loading["81"]={content = "进阶技巧：女王可以卡住对面的远程输出，例如叶子，让她走出去的时候受到伤害",}
cfg_loading["82"]={content = "海皇的深海召唤会把目标朝自己的方向拉3次",}
cfg_loading["83"]={content = "关注排行榜上的高手，学习一下他们的打法",}
cfg_loading["84"]={content = "首充6元，就可获得自带暴击的悟空",}
cfg_loading["85"]={content = "亦燃可以搭配反伤卡牌，释放大招之后反伤可以超过100%",}
cfg_loading["86"]={content = "海皇释放大招时，站位越高越好",}
cfg_loading["87"]={content = "昊释放大招的时候会停留在空中，释放完之后再下落",}
cfg_loading["88"]={content = "开启系统通知可以准时开启宝箱",}
cfg_loading["89"]={content = "昊的飞剑环绕只在敌方回合起效",}
cfg_loading["90"]={content = "格挡是几率触发，成功格挡会减少50%受到的伤害",}
cfg_loading["91"]={content = "亦燃的火焰格挡和卡牌的格挡效果可以同时起效",}
cfg_loading["92"]={content = "计算伤害时，先计算减伤效果，再计算防御效果",}
cfg_loading["93"]={content = "卡牌的暴击效果和悟空的暴击效果可以同时触发",}
cfg_loading["94"]={content = "进阶技巧：昊的大招要掌握好释放距离，而且是斜向下释放",}
cfg_loading["95"]={content = "可爱释放紧急救援时一定要看清楚谁的血量最少",}
cfg_loading["96"]={content = "悟空可以追着打敌方的叶子",}
cfg_loading["97"]={content = "烬君隐身后的暴击只对接下来的第一次伤害起效",}
cfg_loading["98"]={content = "酋长的旋风斩可以把人转飞",}
cfg_loading["99"]={content = "触碰蜂窝之后会刷新蜂窝的中毒效果，所以尽量远离敌方蜂窝",}
cfg_loading["100"]={content = "被冰冻以后无法按左右移动，所以自己飞出去的这种技能要特别小心",}
cfg_loading["101"]={content = "悟空1技能可以在空中调整位置",}
cfg_loading["102"]={content = "可以在系统设置中调整最远镜头的距离",}
cfg_loading["103"]={content = "可以在系统设置中调整镜头是否跟随炮弹，是否跟随玩家",}
cfg_loading["104"]={content = "对战界面也可以查看自己的英雄技能，记得点开屏幕右侧的箭头",}
cfg_loading["105"]={content = "娱乐模式之boss模式：每一方会随机一个50赏金的boss，其余人10赏金",}
cfg_loading["106"]={content = "加载时点击屏幕任意位置会更换提示",}
cfg_loading["107"]={content = "加载时点击屏幕任意位置会更换提示",}
cfg_loading["108"]={content = "加载时点击屏幕任意位置会更换提示",}
cfg_loading["109"]={content = "加载时点击屏幕任意位置会更换提示",}
cfg_loading["110"]={content = "商城金币夺宝360次，可以兑换英雄—昊",}
cfg_loading["111"]={content = "不要害怕死亡，会满血复活的！",}
cfg_loading["112"]={content = "队友有陈可爱的时候可以一起抱团加血。",}
cfg_loading["113"]={content = "匹配、娱乐、排位、人机获胜都可以获得宝箱",}
cfg_loading["114"]={content = "小小打别人脚下可以把别人击飞",}
cfg_loading["115"]={content = "小秋吸别人头部可以吸的更远",}
cfg_loading["116"]={content = "把敌人打到水里可以直接秒杀，除了深海之皇海皇噢",}
cfg_loading["117"]={content = "远程技能通常都受到风力影响，小小的投石和干脆的手雷除外",}
cfg_loading["118"]={content = "护盾卡牌是在每个己方回合开始时增加护盾，最多叠加5层",}
cfg_loading["119"]={content = "吸血卡牌是在反伤卡牌之前结算",}
cfg_loading["120"]={content = "干脆距离敌方比较近的时候可以贴住目标释放手雷",}
cfg_loading["121"]={content = "赏金越高，技能回复的血量也越多",}
cfg_loading["122"]={content = "获得赏金时是有额外生命恢复的，因此给生命很少的队友收人头也不错噢",}
cfg_loading["123"]={content = "拍拍的队友可以尽量把敌人聚到一起，让拍拍一次攻击多个从而快速增加战意层数",}
cfg_loading["124"]={content = "悟空分身可以解除飞镖、蜂窝、标记等不利效果。但是对定时炸弹不太起效…",}
cfg_loading["125"]={content = "队友身上有定时炸弹时，一定要躲的远远的！",}
cfg_loading["126"]={content = "冰女的减速效果对近战英雄的克制作用很强",}
cfg_loading["127"]={content = "试玩模式的一些操作可能在其他模式下无法实现（/阴险）",}
cfg_loading["128"]={content = "队友有肥喵的时候不要着急出手，先观察肥喵！它可能给你加血，加攻，或者和敌人交换位置",}
cfg_loading["129"]={content = "穿过亦燃的燃火之盾时会受到灼烧效果，不要来回穿梭噢！",}
cfg_loading["130"]={content = "昊的飞剑护体可以阻挡敌方的炮弹，甚至对路过的敌方英雄造成伤害",}
cfg_loading["131"]={content = "昊的飞剑护体每回合最多攻击单个敌人6次",}
cfg_loading["132"]={content = "王师傅的火造成4次伤害后就会消失",}
cfg_loading["133"]={content = "吸血、反伤效果最少1点。防御再高也至少会受到1点伤害",}
cfg_loading["134"]={content = "暴击造成的效果是1.5倍伤害，裁决之戒卡牌可以提升暴击伤害",}
cfg_loading["135"]={content = "进阶技巧：敌方王师傅释放定时炸弹后，我方小秋再放大！",}
cfg_loading["136"]={content = "进阶技巧：我方王师傅释放定时炸弹后，叶子可以给目标补上一个标记！",}
cfg_loading["137"]={content = "进阶技巧：不要轻易给小小释放定时炸弹，除非确认他的石化技能在冷却中！",}
cfg_loading["138"]={content = "进阶技巧：王师傅的死亡自爆不受赏金、卡牌、状态影响。",}
cfg_loading["139"]={content = "进阶技巧：王师傅的传送可以作为背水一战的最后武器！",}
cfg_loading["140"]={content = "进阶技巧：敌方王师傅释放定时炸弹后，如果及时击杀王师傅，那么定时炸弹只有基础伤害",}
cfg_loading["141"]={content = "王师傅的火、拍拍的蜂窝、小雷的电墙、女王的恐惧领地都受自身赏金、攻击影响",}
cfg_loading["142"]={content = "小小不要对着墙角放大，放完以后可能自己就上不去了…",}
cfg_loading["143"]={content = "不同英雄的跳跃高度不一样，烬君跳的最高。这时候不提昊…",}
cfg_loading["144"]={content = "防御类英雄受到攻击时会充能大招",}
cfg_loading["145"]={content = "活动界面的邀请好友里面输入邀请码，你和好友可以获得大量奖励",}
cfg_loading["146"]={content = "怦怦活动中有各种福利等大家去领取",}
cfg_loading["147"]={content = "每晚6点-9点登陆游戏并且对战一局，可以获得每日福利宝箱，最高开出666钻石",}
cfg_loading["148"]={content = "每晚6点-9点登陆游戏并且对战一局，可以获得每日福利宝箱，最高开出666钻石",}
cfg_loading["149"]={content = "每晚6点-9点登陆游戏并且对战一局，可以获得每日福利宝箱，最高开出666钻石",}
cfg_loading["150"]={content = "赛特的大招受元素、风力、面向等不同因素影响",}
cfg_loading["151"]={content = "海皇的巨浪可以把队友也顶飞起来",}
cfg_loading["152"]={content = "海皇落到水里可能不死并且随机瞬移",}
cfg_loading["153"]={content = "海皇1技能的攻击范围比其他近战攻击范围大了不止1倍",}
cfg_loading["154"]={content = "进阶技巧：海皇放大前如果生命值充足可选择跳水随机传送，来获得更好的释放位置",}
cfg_loading["155"]={content = "进阶技巧：和队友良好的沟通可以打出完美的配合",}
cfg_loading["156"]={content = "爆炸范围比较大的技能，通常离爆炸中心越近，伤害越高",}
cfg_loading["157"]={content = "使用最大力度攻击敌人，没有推力的技能，也能把敌人击飞一点点距离",}
cfg_loading["158"]={content = "没有最强的英雄，只有最强的玩家",}
cfg_loading["159"]={content = "小秋很全面，适合愿意打配合的玩家",}
cfg_loading["160"]={content = "肥喵翻盘能力很强，要当心噢",}
cfg_loading["161"]={content = "小雷大招对于位置重合的敌人可以造成多倍伤害",}
cfg_loading["162"]={content = "小雷击杀敌方时，会在自身位置释放一道爆炸，要合理利用这次伤害！",}
cfg_loading["163"]={content = "悟空的暴击靠喊！",}
cfg_loading["164"]={content = "游戏的时候认真游戏，学习的时候认真学习！",}
cfg_loading["165"]={content = "叶子要勤加练习！",}
cfg_loading["166"]={content = "实在放不好昊的大招，就贴身放吧…",}
cfg_loading["167"]={content = "小秋可以明显降低敌方攻击力，所以估算自己伤害和敌方威胁时，一定要看清脚下状态",}
cfg_loading["168"]={content = "训练营会教给你一些很实用的技巧",}
cfg_loading["169"]={content = "满星通关初级训练营可以领取干脆皮肤——特种部队！",}
cfg_loading["170"]={content = "试练塔是检验自身能力的好去处！",}
cfg_loading["171"]={content = "试练塔是有些难度的，要搭配好英雄和卡牌，并且熟悉敌方的策略",}
cfg_loading["172"]={content = "每天都可以扫荡试练塔。扫荡积分可以兑换卡牌",}
cfg_loading["173"]={content = "试练塔共100关。100关的敌人是怦怦世界中最强的4位英雄",}
cfg_loading["174"]={content = "副本模式敬请期待",}
cfg_loading["175"]={content = "新增了地图预览功能，选英雄之前可以确认一下地图",}
cfg_loading["176"]={content = "如果你充值了，不要忘记领取首充奖励和月卡！",}
cfg_loading["177"]={content = "多和战队里的小伙伴们一起玩哦，会增加战队活跃度的！",}
cfg_loading["178"]={content = "如果你夺宝出了五个一样的物品，记得截图，这可是小于万分之一的概率！",}
cfg_loading["179"]={content = "策划好像挺喜欢王师傅这个英雄。。。",}
cfg_loading["180"]={content = "碰到怦怦小雷要手下留情！",}
cfg_loading["181"]={content = "英雄的皮肤会增强英雄被动技能。同一个英雄的不同皮肤加强效果是一样的",}
cfg_loading["182"]={content = "升星可以加强英雄技能，每个英雄最多升到5星",}
cfg_loading["183"]={content = "如果你很喜欢一个英雄，要记得给他/她升星哦！",}
cfg_loading["184"]={content = "目前没有妲己这个英雄",}
cfg_loading["185"]={content = "任何卡牌升级都会提升卡牌图鉴经验，卡牌图鉴等级是能力提升最快的部分",}
cfg_loading["186"]={content = "亦燃的防御能力很强，亦燃可以通过商城钻石夺宝的积分兑换来获得",}
cfg_loading["187"]={content = "每日都会获得3次免费金币夺宝的机会！",}
cfg_loading["188"]={content = "紫色卡牌和橙色卡牌会有特殊属性",}
cfg_loading["189"]={content = "每日超值宝箱是性价比最高的！每日只限购一个！",}
cfg_loading["190"]={content = "成长基金可以在活动界面里找到，最高可以获得3600钻石！",}
cfg_loading["191"]={content = "载入提示凑不够100条老板要扣我工资的！（可怜）",}
cfg_loading["192"]={content = "生活和游戏一样，也许坚持住，一切就不一样了！",}
cfg_loading["193"]={content = "局内多次跳水、连续挂机会受到严重的惩罚",}
cfg_loading["194"]={content = "1v1竞技场16级开放，是单人操控4个英雄进行对战，最高12胜可以获得大量升星石",}
cfg_loading["195"]={content = "试练塔每10关会有一个boss关，有些boss关会有些特殊机制",}
cfg_loading["196"]={content = "等级越高，试练塔能控制的英雄越多，最多可以控制4个",}
cfg_loading["197"]={content = "每日的胜利宝箱中会产出两个升星石！",}
cfg_loading["198"]={content = "辅助卡牌指包含反伤、增推、减推的卡牌",}
cfg_loading["199"]={content = "攻击卡牌指包含攻击、暴击、吸血的卡牌",}
cfg_loading["200"]={content = "生命卡牌指包含生命、回复、减伤的卡牌",}
