
--Note: this file is automatically generated by the tool, and manual modifications may be covered; 
--Note: [Common/trunk/proto2lua.bat]
PROTO_MSG = {

-- [enumdefine]Request 

-- [enumdefine]Response 



-- [cmd]Request 
	CS_AccountLogin = {messageID = 21001, name = "CS_AccountLogin"},
	CS_AccountRegister = {messageID = 21002, name = "CS_AccountRegister"},
	CS_CreateRole = {messageID = 21003, name = "CS_CreateRole"},
	CS_EnterGame = {messageID = 21004, name = "CS_EnterGame"},
	CS_EquipMakerBuy = {messageID = 21005, name = "CS_EquipMakerBuy"},
	CS_EquipMakerRefresh = {messageID = 21006, name = "CS_EquipMakerRefresh"},
	CS_GMCmd = {messageID = 21007, name = "CS_GMCmd"},
	CS_Heartbeat = {messageID = 21008, name = "CS_Heartbeat"},
	CS_PlayerEngryPointAssign = {messageID = 21009, name = "CS_PlayerEngryPointAssign"},
	CS_PlayerEngryPointRecycle = {messageID = 21010, name = "CS_PlayerEngryPointRecycle"},
	CS_PlayerEquipPuton = {messageID = 21011, name = "CS_PlayerEquipPuton"},
	CS_PlayerEquipUpgrade = {messageID = 21012, name = "CS_PlayerEquipUpgrade"},
	CS_PlayerEquipUpgradeOneKey = {messageID = 21013, name = "CS_PlayerEquipUpgradeOneKey"},
	CS_ReqPlayerFullInfo = {messageID = 21014, name = "CS_ReqPlayerFullInfo"},
	CS_TopLayer = {messageID = 21015, name = "CS_TopLayer"},

-- [cmd]Response 
	SC_EquipMaker = {messageID = 22001, name = "SC_EquipMaker"},
	SC_GameNoticeList = {messageID = 22002, name = "SC_GameNoticeList"},
	SC_Heartbeat = {messageID = 22003, name = "SC_Heartbeat"},
	SC_KickClientOffline = {messageID = 22004, name = "SC_KickClientOffline"},
	SC_OfflineIncome = {messageID = 22005, name = "SC_OfflineIncome"},
	SC_PlayerFullInfo = {messageID = 22006, name = "SC_PlayerFullInfo"},
	SC_ResAccountLogin = {messageID = 22007, name = "SC_ResAccountLogin"},
	SC_ResAccountRigster = {messageID = 22008, name = "SC_ResAccountRigster"},
	SC_ResCreateRole = {messageID = 22009, name = "SC_ResCreateRole"},
	SC_ResEnterGame = {messageID = 22010, name = "SC_ResEnterGame"},
	SC_ResEquipMakerBuy = {messageID = 22011, name = "SC_ResEquipMakerBuy"},
	SC_ResPlayerCoin = {messageID = 22012, name = "SC_ResPlayerCoin"},
	SC_ResPlayerEngryPointAssign = {messageID = 22013, name = "SC_ResPlayerEngryPointAssign"},
	SC_ResPlayerEngryPointRecycle = {messageID = 22014, name = "SC_ResPlayerEngryPointRecycle"},
	SC_ResPlayerEquipPuton = {messageID = 22015, name = "SC_ResPlayerEquipPuton"},
	SC_ResPlayerEquipUpgrade = {messageID = 22016, name = "SC_ResPlayerEquipUpgrade"},
	SC_ResPlayerEquipUpgradeOneKey = {messageID = 22017, name = "SC_ResPlayerEquipUpgradeOneKey"},
	SC_ResPlayerFullInfo = {messageID = 22018, name = "SC_ResPlayerFullInfo"},
	SC_Tips = {messageID = 22019, name = "SC_Tips"},
	SC_TopLayer = {messageID = 22020, name = "SC_TopLayer"},



-- [battle]Request 
	CS_BattleAccountLogin = {messageID = 31001, name = "CS_BattleAccountLogin"},
	CS_BattleDebugRequest = {messageID = 31002, name = "CS_BattleDebugRequest"},
	CS_ResBattleProxyTask = {messageID = 31003, name = "CS_ResBattleProxyTask"},

-- [battle]Response 
	SC_BattleDebugRequest = {messageID = 32001, name = "SC_BattleDebugRequest"},
	SC_BattleProxyTask = {messageID = 32002, name = "SC_BattleProxyTask"},
	SC_BeginBattle = {messageID = 32003, name = "SC_BeginBattle"},
	SC_ResBattleAccountLogin = {messageID = 32004, name = "SC_ResBattleAccountLogin"},



-- [chat]Request 
	CS_ChatSendMessage = {messageID = 41001, name = "CS_ChatSendMessage"},
	CS_ChatSwitchPublicChannelID = {messageID = 41002, name = "CS_ChatSwitchPublicChannelID"},

-- [chat]Response 
	SC_ChatNotifyMessage = {messageID = 42001, name = "SC_ChatNotifyMessage"},
	SC_ChatPublicChannelInfo = {messageID = 42002, name = "SC_ChatPublicChannelInfo"},
	SC_ChatSync = {messageID = 42003, name = "SC_ChatSync"},



-- [depot]Request 
	CS_DeoptSmelt = {messageID = 51001, name = "CS_DeoptSmelt"},
	CS_DepotLockItem = {messageID = 51002, name = "CS_DepotLockItem"},

-- [depot]Response 
	SC_DepotUpdate = {messageID = 52001, name = "SC_DepotUpdate"},
	SC_Depots = {messageID = 52002, name = "SC_Depots"},
	SC_ResDeoptSmelt = {messageID = 52003, name = "SC_ResDeoptSmelt"},



-- [pet]Request 
	CS_PetCall = {messageID = 61001, name = "CS_PetCall"},
	CS_PetLock = {messageID = 61002, name = "CS_PetLock"},
	CS_PetPlayed = {messageID = 61003, name = "CS_PetPlayed"},
	CS_PetRelease = {messageID = 61004, name = "CS_PetRelease"},
	CS_PetStudy = {messageID = 61005, name = "CS_PetStudy"},

-- [pet]Response 
	SC_PetDepot = {messageID = 62001, name = "SC_PetDepot"},
	SC_ResPetCall = {messageID = 62002, name = "SC_ResPetCall"},
	SC_ResPetPlayed = {messageID = 62003, name = "SC_ResPetPlayed"},
	SC_ResPetStudy = {messageID = 62004, name = "SC_ResPetStudy"},



-- [room]Request 
	CS_Hunting = {messageID = 71001, name = "CS_Hunting"},
	CS_JoinRoom = {messageID = 71002, name = "CS_JoinRoom"},
	CS_ReqPlayerBeRoomMemberInfo = {messageID = 71003, name = "CS_ReqPlayerBeRoomMemberInfo"},
	CS_RoomExplorerList = {messageID = 71004, name = "CS_RoomExplorerList"},
	CS_RoomFastBattle = {messageID = 71005, name = "CS_RoomFastBattle"},
	CS_RoomJoinAuthAllow = {messageID = 71006, name = "CS_RoomJoinAuthAllow"},
	CS_RoomJoinAuthList = {messageID = 71007, name = "CS_RoomJoinAuthList"},
	CS_RoomJoinInviteAllow = {messageID = 71008, name = "CS_RoomJoinInviteAllow"},
	CS_RoomJoinInviteList = {messageID = 71009, name = "CS_RoomJoinInviteList"},
	CS_RoomJoinInvitePlayer = {messageID = 71010, name = "CS_RoomJoinInvitePlayer"},
	CS_RoomMatchInfos = {messageID = 71011, name = "CS_RoomMatchInfos"},
	CS_RoomMemberOption = {messageID = 71012, name = "CS_RoomMemberOption"},
	CS_RoomMemberPetPlayed = {messageID = 71013, name = "CS_RoomMemberPetPlayed"},
	CS_RoomMemberSkillPutOn = {messageID = 71014, name = "CS_RoomMemberSkillPutOn"},
	CS_RoomMemberSkillSwitch = {messageID = 71015, name = "CS_RoomMemberSkillSwitch"},
	CS_RoomSearch = {messageID = 71016, name = "CS_RoomSearch"},
	CS_RoomSetMatchInfo = {messageID = 71017, name = "CS_RoomSetMatchInfo"},
	CS_RoomWait = {messageID = 71018, name = "CS_RoomWait"},

-- [room]Response 
	SC_ReqPlayerBeRoomMemberInfo = {messageID = 72001, name = "SC_ReqPlayerBeRoomMemberInfo"},
	SC_ResRoomFastBattle = {messageID = 72002, name = "SC_ResRoomFastBattle"},
	SC_ResRoomSearch = {messageID = 72003, name = "SC_ResRoomSearch"},
	SC_RoomEventMessageUpdate = {messageID = 72004, name = "SC_RoomEventMessageUpdate"},
	SC_RoomExplorerList = {messageID = 72005, name = "SC_RoomExplorerList"},
	SC_RoomFastBattleInfo = {messageID = 72006, name = "SC_RoomFastBattleInfo"},
	SC_RoomInfo = {messageID = 72007, name = "SC_RoomInfo"},
	SC_RoomJoinAuthList = {messageID = 72008, name = "SC_RoomJoinAuthList"},
	SC_RoomJoinInviteList = {messageID = 72009, name = "SC_RoomJoinInviteList"},
	SC_RoomMatchInfos = {messageID = 72010, name = "SC_RoomMatchInfos"},
	SC_RoomStatusUpdate = {messageID = 72011, name = "SC_RoomStatusUpdate"},



-- [skill]Request 
	CS_PlayerSkillPutOn = {messageID = 81001, name = "CS_PlayerSkillPutOn"},
	CS_PlayerSkillSwitch = {messageID = 81002, name = "CS_PlayerSkillSwitch"},
	CS_PlayerSkillUpgrade = {messageID = 81003, name = "CS_PlayerSkillUpgrade"},

-- [skill]Response 
	SC_PlayerSkillInfo = {messageID = 82001, name = "SC_PlayerSkillInfo"},



-- [mail]Request 
	CS_DeleteMail = {messageID = 91001, name = "CS_DeleteMail"},
	CS_ExtractMailAttachment = {messageID = 91002, name = "CS_ExtractMailAttachment"},
	CS_MarkMailAsRead = {messageID = 91003, name = "CS_MarkMailAsRead"},

-- [mail]Response 
	SC_ResMailList = {messageID = 92001, name = "SC_ResMailList"},


}
