cfg_voiceEvent = cfg_voiceEvent or {}
cfg_voiceEvent["1"]={id = 1,event = "UI_Event_Logo"}
cfg_voiceEvent["2"]={id = 2,event = "UI_Event_Charge"}
cfg_voiceEvent["3"]={id = 3,event = "UI_Event_Charge_Stop"}
cfg_voiceEvent["4"]={id = 4,event = "Vo_Guide_01"}
cfg_voiceEvent["5"]={id = 5,event = "Vo_Guide_02"}
cfg_voiceEvent["6"]={id = 6,event = "Vo_Guide_03"}
cfg_voiceEvent["7"]={id = 7,event = "Vo_Guide_04"}
cfg_voiceEvent["8"]={id = 8,event = "Vo_Guide_05"}
cfg_voiceEvent["9"]={id = 9,event = "Vo_Guide_06"}
cfg_voiceEvent["10"]={id = 10,event = "Vo_Guide_07"}
cfg_voiceEvent["11"]={id = 11,event = "Vo_Guide_08"}
cfg_voiceEvent["12"]={id = 12,event = "Vo_Kill_Double"}
cfg_voiceEvent["13"]={id = 13,event = "Vo_Kill_Triple"}
cfg_voiceEvent["14"]={id = 14,event = "Vo_Kill_Quadruple"}
cfg_voiceEvent["15"]={id = 15,event = "Vo_Kill_KillingSpring"}
cfg_voiceEvent["16"]={id = 16,event = "Vo_Kill_Unstoppable"}
cfg_voiceEvent["17"]={id = 17,event = "Vo_Kill_Dominating"}
cfg_voiceEvent["18"]={id = 18,event = "Vo_Kill_GodLike"}
cfg_voiceEvent["19"]={id = 19,event = "Vo_Kill_Legendary"}
