//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaSpaceComponentWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaSpaceComponent), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("DelayCall", DelayCall);
		L.RegFunction("SetData", SetData);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DelayCall(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaSpaceComponent obj = (LuaSpaceComponent)ToLua.CheckObject<LuaSpaceComponent>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.DelayCall(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaSpaceComponent obj = (LuaSpaceComponent)ToLua.CheckObject<LuaSpaceComponent>(L, 1);
			LuaTable arg0 = ToLua.CheckLuaTable(L, 2);
			obj.SetData(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

