//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_UI_XLoopScrollPrefabSourceWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.UI.XLoopScrollPrefabSource), typeof(System.Object));
		L.RegFunction("InitPool", InitPool);
		L.RegFunction("GetObject", GetObject);
		L.RegFunction("New", _CreateUnityEngine_UI_XLoopScrollPrefabSource);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("prefabGameobj", get_prefabGameobj, set_prefabGameobj);
		L.RegVar("poolSize", get_poolSize, set_poolSize);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_UI_XLoopScrollPrefabSource(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				UnityEngine.UI.XLoopScrollPrefabSource obj = new UnityEngine.UI.XLoopScrollPrefabSource();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1)
			{
				UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 1, typeof(UnityEngine.GameObject));
				UnityEngine.UI.XLoopScrollPrefabSource obj = new UnityEngine.UI.XLoopScrollPrefabSource(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 2)
			{
				UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 1, typeof(UnityEngine.GameObject));
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 2);
				UnityEngine.UI.XLoopScrollPrefabSource obj = new UnityEngine.UI.XLoopScrollPrefabSource(arg0, arg1);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UnityEngine.UI.XLoopScrollPrefabSource.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InitPool(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UI.XLoopScrollPrefabSource obj = (UnityEngine.UI.XLoopScrollPrefabSource)ToLua.CheckObject<UnityEngine.UI.XLoopScrollPrefabSource>(L, 1);
			obj.InitPool();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetObject(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UI.XLoopScrollPrefabSource obj = (UnityEngine.UI.XLoopScrollPrefabSource)ToLua.CheckObject<UnityEngine.UI.XLoopScrollPrefabSource>(L, 1);
			UnityEngine.GameObject o = obj.GetObject();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_prefabGameobj(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UI.XLoopScrollPrefabSource obj = (UnityEngine.UI.XLoopScrollPrefabSource)o;
			UnityEngine.GameObject ret = obj.prefabGameobj;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index prefabGameobj on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_poolSize(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UI.XLoopScrollPrefabSource obj = (UnityEngine.UI.XLoopScrollPrefabSource)o;
			int ret = obj.poolSize;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index poolSize on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_prefabGameobj(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UI.XLoopScrollPrefabSource obj = (UnityEngine.UI.XLoopScrollPrefabSource)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.prefabGameobj = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index prefabGameobj on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_poolSize(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UI.XLoopScrollPrefabSource obj = (UnityEngine.UI.XLoopScrollPrefabSource)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.poolSize = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index poolSize on a nil value");
		}
	}
}

