--- 角色界面视图
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenhaining.
--- DateTime: 2019/11/14 15:48
---
UI_Role = UIPanelBase:new()

function UI_Role:Awake(object)
    UIPanelBase.Awake(self,object)
end

function UI_Role:Start(object)

end

function UI_Role:OnEnable(object)

end
function UI_Role:OnInit(args)
    local btn_back = self:GetObject("btn_back")
    self:AddClickEvent(btn_back, function()
        error("关闭角色界面")
        self:OnClose();
    end)
end

function UI_Role:OnDestroy()
    UIPanelBase.OnDestroy(self)
end