--Note: this file is automatically generated by the tool, and manual modifications may be covered;


--PROTOBUF LIST;
PbManifest =
{ 
    "enumdefine.pb",
    "cmd.pb",
    "battle.pb",
    "chat.pb",
    "depot.pb",
    "pet.pb",
    "room.pb",
    "skill.pb",
    "mail.pb",
}
